# use /w taplo-cli
# format options https://taplo.tamasfe.dev/configuration/formatter-options.html


[[rule]]
include = ["**/Cargo.toml"]

[rule.formatting]
reorder_keys = false
array_auto_collapse = false
array_auto_expand = true
compact_arrays = true
compact_entries = false
allowed_blank_lines = 2
trailing_newline = true
indent_string = "\t"


