[package]
name = "runtime-common"
version = "1.0.0"
authors = ["PAID Network DevHub <https://github.com/PAIDNetwork>"]
edition = "2021"
license = "LGPL-3.0"
homepage = ""
repository = ""

[dependencies]

[features]
default = ["std"]
std = [
]
runtime-benchmarks = [
]
