name: Build Collator

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

env:
  GCP_PROJECT_ID: "paid-network-202104"

jobs:
  compute-image-tag:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ env.IMAGE_TAG }}

    steps:       
      - uses: actions/checkout@v2
      - name: Use Git SHA 
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Use latest
        if: ${{ github.event_name == 'push' }}
        run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV

# TODO: Build Base image when dockerfile.base file changes
  build-collator-image:
    runs-on: ubuntu-latest
    needs: [compute-image-tag]
    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker credentials
        run: gcloud auth configure-docker

      - name: Build image
        run: docker build -t paidnetwork/collator .

      - name: Tag & Publish
        run: |
          docker tag paidnetwork/collator gcr.io/${{ env.GCP_PROJECT_ID }}/collator:${{ needs.compute-image-tag.outputs.IMAGE_TAG }}
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/collator:${{ needs.compute-image-tag.outputs.IMAGE_TAG }}



